### ISSUE TITLE
Have an option on Craft model to generate mutators and accessor .

### ISSUE THREAD

**Issue by mitchdennett** [MasoniteFramework/craft#15]
Have an option on Craft model to generate mutators and accessor. 

The command would create mutators and accessors for all columns of the table. For example 
```
from orator.orm import Model, accessor

class User(Model):

    @accessor
    def first_name(self):
        first_name = self.get_raw_attribute('first_name')

        return first_name[0].upper() + first_name[1:]

    @first_name.mutator
    def set_first_name(self, value):
        self.set_raw_attribute('first_name', value.lower())
```

**Comment by josephmancuso** [comment]
what would the command look like?

```
craft model User --mutators first_name last_name email
```

?

**Comment by mitchdennett** [comment]
Haven't looked into this but it would be nice if it could just get the column names from database.
So the command could just look like this

```
craft model User --someoptionname 
```

**Comment by mitchdennett** [comment]
The reason I was thinking about this is because I can never remember what I call columns and what fields are on the model. The model doesn't currently show this and I keep having to go back to the DB or migration file. This way Intellisense could pick this up etc.

**Comment by josephmancuso** [comment]
hmm i agree that can get annoying. I wonder if we can just add a docstring to it instead .. if the main point is to just know the model definition 🤔 

```
class User(Model):
    """ User definition (generated with love by Masonite)
    
    first_name: varchar(255) default: None
    email: varchar(75) default: None
    active: int() default: 1
    """
    ...
```

thoughts?

**Comment by mitchdennett** [comment]
Yeah thats probably a better way. So just the default command would generate this docstring?

**Comment by josephmancuso** [comment]
yeah .... prob in the terminal so we don't overwrite any docstrings the user has set (if it's even possibly to write a docstring to a class in a .py file)

```
>>> craft model:definition --table users

""" User definition (generated with love by Masonite)
    
first_name: varchar(255) default: None
email: varchar(75) default: None
active: int() default: 1
"""
```

maybe something like that?

**Comment by mitchdennett** [comment]
Well if you're creating a new model there shouldn't be any user generated docstrings right?

```
craft model User
```
That would create a new file.

**Comment by josephmancuso** [comment]
yeah there shouldn't be any changes to existing commands. This should be a whole new command. If you are creating a model, you may or may not have any table definitions or even any tables at all for that model. In fact the model might not even have to connect to a database. I have models I use to connect to API endpoints

**Comment by mitchdennett** [comment]
Makes sense. Then yeah I agree. Just printing it out in the terminal would work 👍

**Comment by josephmancuso** [comment]
yeah then just need to copy paste. I'd like a way to automatically attach the docstring to the model but I think that's more of a hassle than it's worth and not even sure if it's possible. Do you want to take this one or should we present it to the community for anyone to take it?

**Comment by mitchdennett** [comment]
We can present it to the community to give someone an opportunity to contribute. I can do it if no one else wants it though.

**Comment by josephmancuso** [comment]
ok. anyone seeing this, this command should live in the core repo, not in this repo

**Comment by mitchdennett** [comment]
Oops 😉

**Comment by josephmancuso** [comment]
closing and opening the issue in core https://github.com/MasoniteFramework/core/issues/359
