### ISSUE TITLE
[CommandNotFound]: Command "command" is not defined.

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/craft#5]
Using masonite-cli 2.0.7 and trying to create a command;
```
➜ craft command InstallCommand
  [CommandNotFound]
  Command "command" is not defined.
````
This command is not defined in the list of available commands (help, install, list, ew, package). So I think these commands (command, provider) need to be created as mentioned in the documentation. 
[Here](https://docs.masoniteproject.com/the-craft-command/creating-commands) adding the service provider should be done inside `config/application.py`. So what's the purpose of `config/providers.py`.

**Comment by josephmancuso** [comment]
that command should be available to you if you are in your masonite directory and have masonite installed.

**Comment by josephmancuso** [comment]
the craft command only has a few commands but more commands are pulled into craft from the container of your project

**Comment by josephmancuso** [comment]
that should probably be noted in the documentation.

**Comment by josephmancuso** [comment]
Also, the purposes of config/providers.py is to put all providers in 1 place where we can import them into wsgi.py. Masonite 2 makes changes to how providers are structured in order to boost performance. If we imported them into config/application.py then we would have circular import issues as some providers need config variables that are inside this file config/application.py itself. Moving all providers into their own configuration avoids this issue

**Comment by nioperas06** [comment]
So, do we need to update this [section](https://docs.masoniteproject.com/the-craft-command/creating-commands#adding-the-service-provider)?

**Comment by josephmancuso** [comment]
oh snap, yeah! It might be worth while to check other parts of the documentation for mistakes like that.

**Comment by nioperas06** [comment]
Got it! A (full) reading is required 👍 I'm going to do that this weekend. Yes, you're right. Just forgot `craft install` inside the directory 😑. Closed.

**Comment by nioperas06** [comment]
" Many commands are loaded into the framework itself and fetched when craft is ran in a Masonite project directory. This allows version specific Masonite commands to be efficiently handled on each subsequent version as well as third party commands to be loaded in which expands craft itself."
https://docs.masoniteproject.com/the-craft-command/introduction#commands
